package besino.spielzugRules;

public enum ZugTyp {
    KEIN,
    NORMALWEISS,
    NORMALSCHWARZ,
    KILL,
    DAMEWEISSNORMAL,
    DAMESCHWRZNORMAL,
    DAMEWEISSKILL,
    DAMESCHWARZKILL,
    WANDLEDAMEWEISS,
    WANDLEDAMESCHWARZ,
    KILLUNDWANDLEWEISS,
    KILLUNDWANDLESCHWARZ;
}
