package besino.spielzugRules;

public enum ZugTyp {
    KEIN,
    NORMALWEISS,
    NORMALSCHWARZ,
    KILL,
    WANDLEDAMEWEISS,
    WANDLEDAMESCHWARZ,
    KILLUNDWANDLEWEISS,
    KILLUNDWANDLESCHWARZ;
}
